DATABASE_URL="postgresql://postgres.tozhwycrkpwvrmveykbm:2123Footballsjs%231@aws-0-us-west-2.pooler.supabase.com:6543/postgres?pgbouncer=true"
DIRECT_URL="postgresql://postgres.tozhwycrkpwvrmveykbm:2123Footballsjs%231@aws-0-us-west-2.pooler.supabase.com:5432/postgres"
NEXT_PUBLIC_SUPABASE_URL="https://tozhwycrkpwvrmveykbm.supabase.co" NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvemh3eWNya3B3dnJtdmV5a2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMDk5NjcsImV4cCI6MjA4Njg4NTk2N30.Rdkno7ZIew_96x6qVtFYKPC1APxc-U371SJx
     DYz2A"